name: Ruby

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    name: Rubocop
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop

  test:
    name: Ruby
    needs: rubocop
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_kubevirt
      # https://github.com/theforeman/foreman/pull/9989
      foreman_repository: ofedoren/foreman
      foreman_version: foreman-on-ruby-3-letsgooo